### PR TITLE
Ability to load svg in styles

### PR DESCRIPTION
**Pull request by victor192**

### CODE REVIEW

**Comment by thisdp** [comment]
maybe "dgsWindowSetCloseButtonEnabled" should also be affected?

**Comment by victor192** [comment]
Can you explain what you mean?

**Comment by xLive** [comment]
> Can you explain what you mean?

If you use [dgsWindowSetCloseButtonEnabled](https://wiki.mtasa.com/wiki/dgsWindowSetCloseButtonEnabled), you can add the close button back, but it doesn't support the new property **closeButtonImage**
https://github.com/thisdp/dgs/blob/5dd0b3ee19588619b856f8fe08b184bf2d75cbe7/Core/window.lua#L117-L128

thanks for the PR!

**Comment by victor192** [comment]
@thisdp @xLive Fixed

**Comment by thisdp** [comment]
thanks :D

**Pull request merged**
